CREATE DATABASE COLLEGE2;
USE COLLEGE2;

CREATE TABLE STUDENT(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50)
);

CREATE TABLE TEMP2(
  ID INT UNIQUE
);
INSERT INTO TEMP2 
VALUES
(101);

INSERT INTO TEMP2
VALUES
(101);

SELECT * FROM TEMP2;

CREATE TABLE EMPLOYEE(
 ID INT,
 NAME VARCHAR(50),
 SALARY int DEFAULT 2500
 );
 
 SELECT * FROM EMPLOYEE;
 
 INSERT INTO EMPLOYEE(ID, NAME, SALARY)
 VALUES
 (1,'AMEER HAMZA', 1),
 (2,'MUHAMMAD kAMBOH' , 2544);
 
  INSERT INTO EMPLOYEE(ID, NAME)
 VALUES
 (4,'AMEER HAMZA'),
 (3,'MUHAMMAD kAMBOH');
 
 INSERT INTO EMPLOYEE(ID, NAME, SALARY)
 VALUES
 (5,'AMEER HAMZA', 1000),
 (6,'MUHAMMAD kAMBOH' , DEFAULT);
 
  SELECT * FROM EMPLOYEE;
  
CREATE TABLE STUDENT1(
  ID INT, 
  NAME VARCHAR(50), 
  AGE INT CHECK(AGE>=18)
);

INSERT INTO STUDENT1(ID, NAME, AGE)
VALUES
(1,'AMEER',12);

CREATE TABLE CITY(
ID INT PRIMARY KEY,
CITY VARCHAR(60),
AGE INT,
CONSTRAINT AGE_CHECK CHECK(AGE>=18 AND CITY='LHR')
);

SELECT * FROM CITY;


CREATE TABLE STUDENTA(
  ID INT, 
  NAME VARCHAR(50), 
  AGE INT CHECK(AGE>=18)
);

CREATE TABLE STUDENTB(
  ID INT, 
  NAME VARCHAR(50), 
  AGE INT CHECK(AGE>=18)
);

INSERT INTO STUDENTA
VALUES
(1,'AMEER',20),
(1,'HAMZA',18),
(1,'KAMBOH',19);

INSERT INTO STUDENTA
VALUES
(3,'NEXUS',20);

INSERT INTO STUDENTB
VALUES
(3,'NEXUS',20),
(6,'HUN',18),
(8,'MAIN',19);

SELECT * FROM STUDENTA;
SELECT * FROM STUDENTB;
ALTER TABLE STUDENTA;
SET SQL_SAFE_UPDATES = 0;

UPDATE STUDENTA
SET ID=5 WHERE NAME='KAMBOH';

ALTER TABLE STUDENTB
ADD constraint PK_STUDB primary key (ID);

SELECT * FROM STUDENTA 
UNION ALL
SELECT * FROM STUDENTB;

name, basic salary decimal, employe id, bonus decimal, deduction decimal
USE COLLEGE2;

CREATE TABLE EMPLOYES(
    EMPLOYEEID INT PRIMARY KEY,
	NAME VARCHAR(60),
    BSALARY DECIMAL(10,2),
    BONUS DECIMAL(10,2),
    DEDUCTION DECIMAL(10,2)
);

SELECT * FROM EMPLOYES;

INSERT INTO EMPLOYES
VALUES
(1, "AMEER", 250000, 25000, 2500)

INSERT INTO EMPLOYES
VALUES
(2, "HAMZA", 250000, 25000, 2500),
(3, "NEXUS", 34580, 432000, 2323)


SELECT BSALARY+BONUS-DEDUCTION AS TOTAL FROM EMPLOYES;
SELECT BSALARY/12 AS NEWTABLE FROM EMPLOYES;

CREATE TABLE EMPLOYES1(
	EMPLOYEEID INT PRIMARY KEY,
	NAME VARCHAR(60),
    BSALARY DECIMAL(10,2),
    BONUS DECIMAL(10,2),
    DEDUCTION DECIMAL(10,2)
    );
    
INSERT INTO EMPLOYES1
VALUES
(4, "KHURRAM", 2342, 3142,1331),
(5, "KHALID", 323232, 1343,35312);

SELECT * FROM EMPLOYES1
WHERE (BONUS BETWEEN 1000 AND 2000);


CREATE TABLE CONCATINATE(
NAME VARCHAR(59),
FNAME VARCHAR(80)
);

INSERT INTO CONCATINATE
VALUES
('AMEER', 'RASHID'),
('ALI', 'KHALID');

SELECT CONCAT(NAME,' ',FNAME) AS COLLECTION FROM CONCATINATE;


