-- Nested Queries
CREATE DATABASE UNI;

USE UNI;

CREATE TABLE STUDENT(
ID INT,
NAME VARCHAR(59),
MARKS INT,
GRADE VARCHAR(3),
CITY VARCHAR(50)
);

INSERT INTO STUDENT
VALUES
(101, "ALI" , 92, "A", "LAHORE"),
(102, "ANUM", 85, "B+", "LAHORE"),
(103, "HAMZA", 76, "B", "KARACHI"),
(104, "BUSHRA", 89, "A-", "ISLAMABAD"),
(105, "ALIA", 91, "A", "KARACHI"),
(106, "SAAD", 66, "C+", "LAHORE"),
(107, "AYESHA", 54, "C", "KARACHI");


SELECT SUM(MARKS)/COUNT(*) FROM STUDENT;

SELECT NAME FROM STUDENT
WHERE MARKS > A;

SELECT NAME, ID FROM STUDENT 
WHERE ID%2=0;


SELECT NAME, ID FROM STUDENT WHERE ID IN
(SELECT ID FROM STUDENT WHERE ID%2=0);

SELECT MAX(MARKS) FROM STUDENT;

SELECT * FROM STUDENT WHERE CITY="LAHORE" AND MARKS = (SELECT MAX(MARKS) FROM STUDENT);

SELECT MAX(MARKS) FROM (SELECT * FROM STUDENT WHERE CITY="LAHORE") AS C;

SELECT NAME, (SELECT MAX(MARKS) FROM STUDENT AS MARKS) 
FROM STUDENT WHERE CITY="LAHORE";