CREATE DATABASE UNIVERSITY;
USE UNIVERSITY;
CREATE TABLE STUDENT(
NAME VARCHAR(50),
ID INT);

CREATE TABLE FEE(
ID INT,
AMOUNT INT,
MODE VARCHAR(50),
PAYMENTDATE DATE);

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS
VALUES
("AMEER", 1),
("HAMZA", 2);

INSERT INTO STUDENTS
VALUES 
("KAMBOH", 3);

INSERT INTO FEE
VALUES
(1, 100000, "ONLINE", "2023-2-2"),
(2, 25000, "PHYSICAL", "2024-5-1");

SELECT F.AMOUNT, F.MODE, F.PAYMENTDATE FROM FEE F
INNER JOIN 
STUDENTS S ON S.ID = F.ID
WHERE 
S.SNAME = "AMEER";

-- RENAME TABLE

ALTER TABLE STUDENT
RENAME STUDENTS;

-- CHANGE COLUMN NAME

ALTER TABLE STUDENTS
CHANGE COLUMN NAME SNAME VARCHAR(50);

-- ADD COLUMN

ALTER TABLE STUDENTS
ADD COLUMN AGE INT;

-- DROP COLUMN

ALTER TABLE STUDENTS
DROP COLUMN AGE;



SELECT * FROM STUDENTS AS S
LEFT JOIN
FEE AS F ON F.ID = S.ID
UNION
SELECT * FROM FEE AS F
LEFT JOIN 
STUDENTS AS S ON F.ID = S.ID;