CREATE DATABASE SCHOOL;

USE SCHOOL;

CREATE TABLE STUDENT(
NAME VARCHAR(50),
ROLLNO INT,
MARKS INT,
GRADE VARCHAR(50),
CITY VARCHAR(50)
);

INSERT INTO STUDENT
VALUES
("AMEER",1, 100, 'A', "LAHORE"),
("HAMZA", 2, 46, 'A', "KARACHI"),
("KAMBOH", 3, 56, 'B', "FAISALABAD"),
("KHURRAM",4, 90, 'A', "LAHORE"),
("ALI", 5, 36, 'A', "KARACHI"),
("BABAR", 6, 16, 'B', "FAISALABAD");

SELECT * FROM STUDENT;
SET SQL_SAFE_UPDATES = 0;

UPDATE STUDENT
SET MARKS = MARKS + 5;

SELECT NAME, MARKS, MARKS*2 AS DOUBLEMARKS FROM STUDENT;

SELECT NAME, MARKS, MARKS/2 AS DIVIDEMARKS FROM STUDENT;

SELECT NAME, MARKS FROM STUDENT WHERE MARKS>=51;

UPDATE STUDENT 
SET NAME = "BABAR AZAM" WHERE NAME = "BABAR";

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE CITY != "KARACHI" OR CITY = "LAHORE";

SELECT * FROM STUDENT WHERE NAME NOT IN ("AMEER", "BABAR AZAM");

SELECT * FROM STUDENT WHERE NAME IN ("AMEER", "BABAR AZAM");

SELECT * FROM STUDENT WHERE MARKS<59 LIMIT 3;

SELECT NAME, MARKS, (MARKS AND 1) AS BITWISENOT
FROM STUDENT;

SELECT ROLLNO,CITY, COUNT(*) AS count
FROM STUDENT WHERE CITY = "LAHORE"
GROUP BY CITY;

SELECT NAME, CITY, COUNT(*) AS count
FROM STUDENT
WHERE CITY = 'LAHORE'
GROUP BY CITY,NAME;

SELECT NAME, CITY, COUNT(*) AS count
FROM STUDENT
GROUP BY CITY,NAME
;

 
 
 
 
 
 
 
 
 
 